### ISSUE TITLE
There are duplicate data

### ISSUE THREAD

**Issue by elgeekim** [ziegler-ingo/cleavage_prediction#1]
I concatenated the train, valid and test set both nterm and cterm cleavage dataset and then analyzed.
The total dataset of nterm cleavage is 1434989, but unique cleavage window is only 1417900.
Some of duplicated data have different labels.
Is there any resons you did this?

**Comment by ziegler-ingo** [comment]
Hello,

due to the way proteasomal cleavage events are constructed and inferred, noise and randomness can occur. The base dataset, which was introduced in [1], was cut and shuffled in multiple ways with varying sequence lengths from longer and continuous sequences. For instance, here we used length 10 sequences, but in other scenarios the sequences could be 14, 21, 28, etc. We ran some experiments with those longer sequences here [2].
What may appear as a standalone sequence here with a certain label, might just be one specific cut of a shuffle result of longer sequences with other labels.

De-duplication of the original (very long) sequences has already happened at time of dataset construction, as described in [1], or [3], i.e. this paper. At that point, we accounted for duplicate sequences, everything after that is just "part of the experiment". 


[1] https://arxiv.org/pdf/2209.07527.pdf
[2] https://github.com/ziegler-ingo/cleavage_extended
[3] https://arxiv.org/abs/2210.12991
